-- Try to replicate the leyline effect

INSERT OR IGNORE INTO Modifiers
		(ModifierId, ModifierType,SubjectRequirementSetId,OwnerRequirementSetId)
VALUES  ('BOOST_LEYLINE_MODIFIER', 'MODIFIER_GAME_ADJUST_PLOT_YIELD', 'PLOT_ADJACENT_TO_RIVER_REQUIREMENTS', Null);

INSERT OR IGNORE INTO DynamicModifiers
		(ModifierType, CollectionType, EffectType)
VALUES	('BOOST_LEYLINE_MODIFIER', 'COLLECTION_OWNER', 'EFFECT_ADJUST_PLAYER_YIELD_MODIFIER_PER_EARNED_GREAT_PERSON');
--VALUES	('BOOST_LEYLINE_MODIFIER', 'COLLECTION_OWNER', 'EFFECT_ADJUST_PLAYER_YIELD_CHANGE_PER_GREAT_PERSON_CLASS_ON_RESOURCE');
-- Link the two boosts
INSERT OR IGNORE INTO Modifiers
		(ModifierId, ModifierType)
VALUES  ('RIVER_SCIENCE_BOOST_LEYLINE_MODIFIER', 'BOOST_LEYLINE_MODIFIER');

-- Define the type of the boost
INSERT OR IGNORE INTO Types
		(Type, Kind)
VALUES  ('BOOST_LEYLINE_MODIFIER', 'KIND_MODIFIER');

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId, Name, Value)
VALUES	('RIVER_SCIENCE_BOOST_LEYLINE_MODIFIER', 'Amount' , 5),
		('RIVER_SCIENCE_BOOST_LEYLINE_MODIFIER', 'YieldType' , 'YIELD_SCIENCE'),
		--('RIVER_SCIENCE_BOOST_LEYLINE_MODIFIER', 'GreatPersonClassType' , 'GREAT_PERSON_CLASS_ARTIST'),
		--('RIVER_SCIENCE_BOOST_LEYLINE_MODIFIER', 'TerrainType' , 'TERRAIN_GRASS');
		--('RIVER_SCIENCE_BOOST_LEYLINE_MODIFIER', 'ResourceType' , 'RESOURCE_STONE');


--INSERT OR IGNORE INTO GovernorPromotionModifiers
--		(GovernorPromotionType, ModifierId)
--VALUES	('GOVERNOR_PROMOTION_HERMETIC_ORDER_1', 'RIVER_SCIENCE_BOOST_LEYLINE_MODIFIER');

INSERT OR IGNORE INTO GameModifiers
		(ModifierId)
VALUES	('RIVER_SCIENCE_BOOST_LEYLINE_MODIFIER');
