DELETE FROM Resource_YieldChanges;

INSERT OR IGNORE INTO Resource_YieldChanges
		(ResourceType,YieldType,YieldChange)
VALUES	
		-- Food Plants -- Farm
		('RESOURCE_RICE','YIELD_FOOD',3),
		('RESOURCE_WHEAT','YIELD_FOOD',3),
		('RESOURCE_MAIZE','YIELD_FOOD',3),

		-- Food Plants -- Plantation
		('RESOURCE_BANANAS','YIELD_FOOD',3),	
		('RESOURCE_CITRUS','YIELD_FOOD',3),

		-- Luxury Plants -- Food -- Plantation
		('RESOURCE_SPICES','YIELD_CULTURE',2),
		('RESOURCE_SPICES','YIELD_GOLD',1),
		('RESOURCE_SUGAR','YIELD_FOOD',2),
		('RESOURCE_WINE','YIELD_GOLD',2),
		('RESOURCE_WINE','YIELD_CULTURE',1),
		-- Luxury plants -- Plantation		
		('RESOURCE_COCOA','YIELD_GOLD',3),
		('RESOURCE_COTTON','YIELD_GOLD',3),	

		('RESOURCE_OLIVES','YIELD_GOLD',1),
		('RESOURCE_OLIVES','YIELD_PRODUCTION',1),

		('RESOURCE_COFFEE','YIELD_CULTURE',3),

		('RESOURCE_TEA','YIELD_SCIENCE',3),
	
		('RESOURCE_TOBACCO','YIELD_FAITH',3),	
		('RESOURCE_DYES','YIELD_FAITH',3),
		('RESOURCE_INCENSE','YIELD_FAITH',3),

		--Domesticated Animals
		('RESOURCE_CATTLE','YIELD_FOOD',1),		
		('RESOURCE_CATTLE','YIELD_PRODUCTION',1),		
	    ('RESOURCE_SHEEP','YIELD_FOOD',2),

		--Bonus Animals - Fishing
		('RESOURCE_CRABS','YIELD_FOOD',2),	
		('RESOURCE_FISH','YIELD_FOOD',2),	

		-- Bonus Animals - Camp
		('RESOURCE_DEER','YIELD_FOOD',2),
		-- Luxury Animals - Camp
		('RESOURCE_HONEY','YIELD_FOOD',2),
		
		('RESOURCE_IVORY','YIELD_SCIENCE',1),
		('RESOURCE_IVORY','YIELD_PRODUCTION',1),
		
		('RESOURCE_FURS','YIELD_GOLD',2),
		('RESOURCE_TRUFFLES','YIELD_GOLD',2),

		('RESOURCE_TURTLES','YIELD_SCIENCE',2),
		('RESOURCE_WHALES','YIELD_SCIENCE',3),

		('RESOURCE_HORSES','YIELD_PRODUCTION',2),
		--Minerals Food
		('RESOURCE_SALT','YIELD_FOOD',1),
		('RESOURCE_SALT','YIELD_GOLD',1),				
		-- Fertilizer Mineral
		('RESOURCE_GYPSUM','YIELD_FOOD',2),
		-- Industry Mineral
		('RESOURCE_COPPER','YIELD_PRODUCTION',2),
		('RESOURCE_STONE','YIELD_PRODUCTION',2),
		('RESOURCE_IRON','YIELD_PRODUCTION',2),
		('RESOURCE_SILVER','YIELD_GOLD',3),
		('RESOURCE_MERCURY','YIELD_SCIENCE',3),
		--Renaissance Era Ressource
		('RESOURCE_NITER','YIELD_PRODUCTION',3),
		--Industrial Era Ressource
		('RESOURCE_COAL','YIELD_PRODUCTION',4),
		--Modern Era Ressource
		('RESOURCE_ALUMINUM','YIELD_PRODUCTION',5),
		('RESOURCE_OIL','YIELD_PRODUCTION',5),
		--Atomic Era Ressource
		('RESOURCE_URANIUM','YIELD_SCIENCE',3),
		
		-- Luxury Mineral
		('RESOURCE_DIAMONDS','YIELD_GOLD',3),
		('RESOURCE_JADE','YIELD_GOLD',3),
		('RESOURCE_PEARLS','YIELD_GOLD',3),
		('RESOURCE_SILK','YIELD_GOLD',3),

		('RESOURCE_MARBLE','YIELD_CULTURE',3),
		('RESOURCE_AMBER','YIELD_CULTURE',3);