DELETE FROM Terrain_YieldChanges;

INSERT OR IGNORE INTO Terrain_YieldChanges
		(TerrainType,YieldType,YieldChange)
VALUES	('TERRAIN_COAST','YIELD_FOOD',2),
		('TERRAIN_GRASS','YIELD_FOOD',2),
		('TERRAIN_TUNDRA','YIELD_FOOD',1),	
		('TERRAIN_PLAINS','YIELD_PRODUCTION',1),
		('TERRAIN_GRASS_RIVER','YIELD_SCIENCE',10),
		('TERRAIN_SNOW_HILLS','YIELD_PRODUCTION',1),
		('TERRAIN_GRASS_HILLS','YIELD_PRODUCTION',1),
		('TERRAIN_TUNDRA_HILLS','YIELD_PRODUCTION',1),		
		('TERRAIN_DESERT_HILLS','YIELD_PRODUCTION',1),
		('TERRAIN_PLAINS_HILLS','YIELD_PRODUCTION',2);
